---

- name: Create stretch-backports apt config
  copy:
    content: |
      deb http://deb.debian.org/debian stretch-backports main contrib non-free
    dest: /etc/apt/sources.list.d/stretch-backports.list
    owner: root
    group: root
    mode: 0644
  become: yes
  notify:
    - apt update cache
  tags:
    - prometheus
    - prometheus_deploy

- meta: flush_handlers

- name: Install node exporter (from stretch-backports)
  apt:
    name:
      - prometheus-node-exporter
    default_release: stretch-backports
  become: yes
  when: prometheus_install_node_exporter
  tags:
    - prometheus
    - prometheus_deploy

- name: Install prometheus (from stretch-backports)
  apt:
    name:
      - prometheus
    default_release: stretch-backports
  become: yes
  when: prometheus_install_server or prometheus_version == "default"
  tags:
    - prometheus
    - prometheus_deploy

- block:
    - name: Downloading prometheus (from Official github repo)
      become: false
      get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-{{ go_arch }}.tar.gz"
        dest: "/tmp/prometheus-{{ prometheus_version }}.linux-{{ go_arch }}.tar.gz"
        checksum: "sha256:{{ prometheus_checksum }}"
      register: _download_archive
      until: _download_archive is succeeded
      retries: 5
      delay: 2
      # run_once: true # <-- this cannot be set due to multi-arch support
      delegate_to: localhost
      check_mode: false

    - name: unpack prometheus binaries
      become: false
      unarchive:
        src: "/tmp/prometheus-{{ prometheus_version }}.linux-{{ go_arch }}.tar.gz"
        dest: "/tmp"
        creates: "/tmp/prometheus-{{ prometheus_version }}.linux-{{ go_arch }}/prometheus"
      check_mode: false

    - name: propagate official prometheus and promtool binaries
      copy:
        src: "/tmp/prometheus-{{ prometheus_version }}.linux-{{ go_arch }}/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        mode: 0755
        owner: root
        group: root
      with_items:
        - prometheus
        - promtool
      notify:
        - restart prometheus

    - name: propagate official console templates
      copy:
        src: "/tmp/prometheus-{{ prometheus_version }}.linux-{{ go_arch }}/{{ item }}/"
        dest: "{{ prometheus_config_dir }}/{{ item }}/"
        mode: 0644
        owner: root
        group: root
      with_items:
        - console_libraries
        - consoles
      notify:
        - restart prometheus
  when: prometheus_version != "default"

- name: Enable prometheus-node-exporter
  systemd:
    name: prometheus-node-exporter
    enabled: yes
  become: yes
  when: prometheus_install_node_exporter
  tags:
    - prometheus
    - prometheus_deploy

- name: Start prometheus-node-exporter
  systemd:
    name: prometheus-node-exporter
    state: started
  become: yes
  register: start_prometheus_node_exporter
  when: prometheus_install_node_exporter
  tags:
    - prometheus
    - prometheus_deploy

- name: Enable prometheus
  systemd:
    name: prometheus
    enabled: yes
  become: yes
  when: prometheus_install_server
  tags:
    - prometheus
    - prometheus_deploy

- name: Start prometheus
  systemd:
    name: prometheus
    state: started
  become: yes
  register: start_prometheus
  when: prometheus_install_server
  tags:
    - prometheus
    - prometheus_deploy
