---

- name: Create stretch-backports apt config
  copy:
    content: |
      deb http://deb.debian.org/debian stretch-backports main contrib non-free
    dest: /etc/apt/sources.list.d/stretch-backports.list
    owner: root
    group: root
    mode: 0644
  become: yes
  notify:
    - apt update cache
  tags:
    - prometheus
    - prometheus_deploy

- meta: flush_handlers

- name: Install node exporter (from stretch-backports)
  apt:
    name:
      - prometheus-node-exporter
    default_release: stretch-backports
  become: yes
  when: prometheus_install_node_exporter
  tags:
    - prometheus
    - prometheus_deploy

- name: Install prometheus (from stretch-backports)
  apt:
    name:
      - prometheus
    default_release: stretch-backports
  become: yes
  when: prometheus_install_server
  tags:
    - prometheus
    - prometheus_deploy

- name: Enable prometheus-node-exporter
  systemd:
    name: prometheus-node-exporter
    enabled: yes
  become: yes
  when: prometheus_install_node_exporter
  tags:
    - prometheus
    - prometheus_deploy

- name: Start prometheus-node-exporter
  systemd:
    name: prometheus-node-exporter
    state: started
  become: yes
  register: start_prometheus_node_exporter
  when: prometheus_install_node_exporter
  tags:
    - prometheus
    - prometheus_deploy

- name: Enable prometheus
  systemd:
    name: prometheus
    enabled: yes
  become: yes
  when: prometheus_install_server
  tags:
    - prometheus
    - prometheus_deploy

- name: Start prometheus
  systemd:
    name: prometheus
    state: started
  become: yes
  register: start_prometheus
  when: prometheus_install_server
  tags:
    - prometheus
    - prometheus_deploy
