---
- name: restart prometheus
  systemd:
    name: prometheus
    state: restarted
  become: yes
  when: prometheus_install_server
  tags:
    - prometheus
    - prometheus_deploy

- name: restart node_exporter
  systemd:
    name: node_exporter
    state: restarted
  become: yes
  tags:
    - prometheus
    - prometheus_deploy

- name: systemctl reload
  systemd:
    daemon_reload: yes
  become: yes
  tags:
    - prometheus
    - prometheus_deploy

- name: restart alertmanager
  docker_service:
    project_src: "{{ prometheus_docker_dir }}"
    state: present
    restarted: yes
    services: alertmanager
  become: yes
  become_user: "{{ prometheus_docker_user }}"
  tags:
    - prometheus
    - prometheus_deploy
