---
# handlers file for prometheus

- name: restart prometheus
  systemd:
    name: prometheus
    state: reloaded
  become: yes
  when: 


- name: systemctl reload
  systemd:
    daemon_reload: yes
  become: yes
